Add Turkish Language
simonwep/ocular pull request #40
Opened 2024-05-11 23:20 UTC by TaylanTatli

2024-05-12 08:12 UTC, simonwep requested changes
Hey! Thank you for your contribution :)

- [x] Please use conventional commit messages, e.g. `feat: add turkish language` instead of "Add Turkish Language" :)
- [x] Keep the same order of keys in `tr.json` as compared to the other files. Makes it easier to review.
- [ ] Run the `test:ci` script locally, I'm not sure why the `build` job in the workflow wasn't triggered by your PR. But the build fails.

2024-05-12 12:29 UTC, TaylanTatli commented
I did everything you told me. It should be good to go. But I forced pushed to commit to change last commit. I don't know what to do about this requested changes. I don't have much knowledge about Git.

2024-05-15 16:04 UTC, simonwep commented
> I did everything you told me. It should be good to go. But I forced pushed to commit to change last commit. I don't know what to do about this requested changes. I don't have much knowledge about Git.

Hey, no problem. You can just check the checkboxes I made - I did that for you in this case. I'm working on contributing guidelines, so don't worry. I checked out your PR, rebased it and fixed a small bug with `_numberFormats`, you didn't have to translate that part :)

I'll merge yours in the coming day. Thank you for your contribution ❤️

2024-05-20 11:42 UTC, simonwep approved these changes

2024-05-20 11:45 UTC, merged